In [37]:
import pandas as pd
posições=[]
coordenadas=[]


for alt in range(1,4):
    for larg in range(1,4):
        for prof in range(1,4):

            posições.append({'altura':alt,'largura':larg,'profundidade':prof})
            
cubo=pd.DataFrame(posições)


cubo.loc[cubo['altura']==3,'U']='amarelo'
cubo.loc[cubo['largura']==1,'L']='verde'
cubo.loc[cubo['profundidade']==1,'F']='laranja'
cubo.loc[cubo['largura']==3,'R']='azul'
cubo.loc[cubo['profundidade']==3,'B']='vermelho'
cubo.loc[cubo['altura']==1,'D']='branco'


for i in range(len(cubo)):
    coordenadas.append([cubo['altura'][i],cubo['largura'][i],cubo['profundidade'][i]])

for j in coordenadas:
    
    if j.count(2)==3:
        cubo.loc[coordenadas.index(j),'tipo']='nucleo'
        
    elif j.count(2)==0:
        cubo.loc[coordenadas.index(j),'tipo']='quina'

    elif j.count(2)==2:
        cubo.loc[coordenadas.index(j),'tipo']='centro'
    
    else:
        cubo.loc[coordenadas.index(j),'tipo']='meio'


cubo.drop(cubo.loc[cubo['tipo']=='centro'].index,axis=0,inplace=True)
cubo.drop(cubo.loc[cubo['tipo']=='nucleo'].index,axis=0,inplace=True)

cubo.reset_index(inplace=True,drop=True)


ciclo_U=cubo.loc[[14,16,19,18,17,15,12,13]]
ciclo_L=cubo.loc[[14,13,12,8,0,1,2,9]]
ciclo_F=cubo.loc[[12,15,17,10,5,3,0,8]]
ciclo_R=cubo.loc[[17,18,19,11,7,6,5,10]]
ciclo_B=cubo.loc[[19,14,16,9,2,4,7,11]]
ciclo_D=cubo.loc[[0,3,5,6,7,4,2,1]]



rotação=pd.concat([ciclo_L[2:],ciclo_L[:2]])


ciclo_L.reset_index(inplace=True)
rotação.reset_index(inplace=True)

display(ciclo_L)
display(rotação)

ciclo_L.loc[:,1:3]=rotação.loc[:,1:3]

,index,altura,largura,profundidade,U,L,F,R,B,D,tipo
0,14,3,1,3,amarelo,verde,NaN,NaN,vermelho,NaN,quina
1,13,3,1,2,amarelo,verde,NaN,NaN,NaN,NaN,meio
2,12,3,1,1,amarelo,verde,laranja,NaN,NaN,NaN,quina
3,8,2,1,1,NaN,verde,laranja,NaN,NaN,NaN,meio
4,0,1,1,1,NaN,verde,laranja,NaN,NaN,branco,quina
5,1,1,1,2,NaN,verde,NaN,NaN,NaN,branco,meio
6,2,1,1,3,NaN,verde,NaN,NaN,vermelho,branco,quina
7,9,2,1,3,NaN,verde,NaN,NaN,vermelho,NaN,meio

,index,altura,largura,profundidade,U,L,F,R,B,D,tipo
0,12,3,1,1,amarelo,verde,laranja,NaN,NaN,NaN,quina
1,8,2,1,1,NaN,verde,laranja,NaN,NaN,NaN,meio
2,0,1,1,1,NaN,verde,laranja,NaN,NaN,branco,quina
3,1,1,1,2,NaN,verde,NaN,NaN,NaN,branco,meio
4,2,1,1,3,NaN,verde,NaN,NaN,vermelho,branco,quina
5,9,2,1,3,NaN,verde,NaN,NaN,vermelho,NaN,meio
6,14,3,1,3,amarelo,verde,NaN,NaN,vermelho,NaN,quina
7,13,3,1,2,amarelo,verde,NaN,NaN,NaN,NaN,meio

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [3]:
display(ciclo_L)

,altura,largura,profundidade,U,L,F,R,B,D,tipo
14,3,1,3,amarelo,verde,NaN,NaN,vermelho,NaN,quina
13,3,1,2,amarelo,verde,NaN,NaN,NaN,NaN,meio
12,3,1,1,amarelo,verde,laranja,NaN,NaN,NaN,quina
8,2,1,1,NaN,verde,laranja,NaN,NaN,NaN,meio
0,1,1,1,NaN,verde,laranja,NaN,NaN,branco,quina
1,1,1,2,NaN,verde,NaN,NaN,NaN,branco,meio
2,1,1,3,NaN,verde,NaN,NaN,vermelho,branco,quina
9,2,1,3,NaN,verde,NaN,NaN,vermelho,NaN,meio

'BERNARDO SILVA CASTRO'